spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: user
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/user_labourconnect
    username: postgres
    password: '1205'
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true