
spring:
  application:
    name: notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: shoose.greetings@gmail.com
    password: ylsm nbmc ryxv czsy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
server:
  port: 8082
  servlet:
    context-path: '/notification'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true