server:
  port: 8080
spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
#      routes:
#        - id: AUTH
#          predicates:
#            - Path=/auth/**
#          uri: lb://auth
#        - id: notification
#          predicates:
#            - Path=/notification/**
#          uri: "localhost:8082"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
