server:
  port: 8084
spring:
  application:
    name = booking
  zipkin:
    base-url: http://localhost:9411
  data:
    mongodb:
      host: localhost
      port: 27017
      database: booking-service

