package com.example.booking.model.entity;

public enum Status {
    REQUESTED,
    CONFIRMED,
    REJECTED,
    REQUESTED_OR_CANCELLATION,
    CANCELLED,
    REQUESTED_FOR_RESCHEDULE,
    RESCHEDULE_REQUEST_REJECTED,
    RESCHEDULED,
    COMPLETED
}
